# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AndersBill.com
email: anders@darkroom.tech
description: > # this means to ignore newlines until "baseurl:"
  I've had a passion for creating companies that have the potential to empower other entrepreneurs,
  whether they be musicians, photographers, or engineers. 
  My past/current ventures are based off the thesis that the future is one of mass
  decentralization: of power, communication and security.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
